### ISSUE TITLE
Following instuctions from the readme fails when importing private key

### ISSUE THREAD

**Issue by wanderer** [jb55/clightning-dumpkeys#1]
if you follow the instructions in the readme on importing your private key, it will fail. 

According to the readme the description.json should look like this.
```
[
  {
    "desc": "combo(xprv ... /*)",
    "keypool": true,
    "timestamp": "now",
    "watchonly": false,
    "internal": false,
    "range": [0, 1000]
  }
]
``` 
when trying to import it with `bitcoin-cli -rpcwallet=clightning importmulti "$(cat ./descriptors.json)" '{"rescan": false}'`
results in 

```
[
  {
    "success": false,
    "error": {
      "code": -8,
      "message": "Keys can only be imported to the keypool when private keys are disabled"
    }
  }
]
```

**Comment by jb55** [comment]
you're right, it's missing the watchonly argument on the createwallet step. thanks!
